# Generated by Django 4.0.3 on 2022-03-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='gender',
        ),
    ]
